### ISSUE TITLE
Wrong quantity

### ISSUE THREAD

**Issue by Th0rgal** [Th0rgal/binance.py#22]
Hello @Ma007ks,

I have an issue with your commits. I'm using the testnet and I want to buy ETH with 10% of my BTC balance.
With your commits (1.8.1):
```
>> {'symbol': 'ETHBTC', 'side': <Side.BUY: 'BUY'>, 'order_type': <OrderType.MARKET: 'MARKET'>, 'quote_order_quantity': Decimal('0.090569718')}
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<BotsPooler.send_order() done, defined at ./botspooler.py:176> exception=BinanceError('Invalid quantity.')>
Traceback (most recent call last):
  File "./botspooler.py", line 178, in send_order
    order = await user.client.create_order(**kwargs)
  File "/nix/store/bg993hfs0dw6vqq1qfci9241950qgwn8-python3-3.8.9-env/lib/python3.8/site-packages/binance/client.py", line 368, in create_order
    return await self.http.send_api_call(route, "POST", data=params, signed=True)
  File "/nix/store/bg993hfs0dw6vqq1qfci9241950qgwn8-python3-3.8.9-env/lib/python3.8/site-packages/binance/http.py", line 84, in send_api_call
    return await self.handle_errors(response)
  File "/nix/store/bg993hfs0dw6vqq1qfci9241950qgwn8-python3-3.8.9-env/lib/python3.8/site-packages/binance/http.py", line 47, in handle_errors
    raise BinanceError(payload["msg"])
binance.errors.BinanceError: Invalid quantity.
```

With the previous build (1.8.0), I tried with even 1%:
{'symbol': 'ETHBTC', 'side': <Side.BUY: 'BUY'>, 'order_type': <OrderType.MARKET: 'MARKET'>, 'quote_order_quantity': Decimal('0.0090569718')}

and it worked perfectly. 
Do you have any idea of what causes that issue? I will probably revert you commits for now.

Thomas

**Comment by Ma007ks** [comment]
Hello @Th0rgal!

1. Have you tried current build with 1%?
2. Have you tried previous build with 10%?

**Comment by Th0rgal** [comment]
> Hello @Th0rgal!
> 
> 1. Have you tried current build with 1%?
> 2. Have you tried previous build with 10%?

Hey, I appreciate the quick answer!

Yes I did but because it worked one time with the second build, the quantity changed (1% of 100 is not 1% of 99), but I got a problem for every test with the new build and no problem at all with the previous one.

**Comment by Ma007ks** [comment]
> Yes I did but because it worked one time with the second build, the quantity changed (1% of 100 is not 1% of 99), but I got a problem for every test with the new build and no problem at all with the previous one.

We can be sure that the order creation request was sent and then server sent the error. There is can be a problem with the maximum quantity allowed. 

Could you check what the client really send in `send_api_call`?

**Comment by Th0rgal** [comment]
Alright, I'm checking

> > Yes I did but because it worked one time with the second build, the quantity changed (1% of 100 is not 1% of 99), but I got a problem for every test with the new build and no problem at all with the previous one.
> 
> We can be sure that the order creation request was sent and then server sent the error. There is can be a problem with the maximum quantity allowed.
> 
> Could you check what the client really send in `send_api_call`?

When I print the refined_amount from the last version, I get 0.

**Comment by Ma007ks** [comment]
Whoops 👀
Tbh I don't remember why I make a special case for quote but it's a cause https://github.com/Th0rgal/binance.py/blob/bdaab0c29abd55f030325e88f38699ac605a7884/binance/client.py#L98
